export const env = {
  nodeEnv: process.env.NODE_ENV ?? "development",
  port: Number(process.env.PORT ?? 3001),
  databaseUrl: process.env.DATABASE_URL ?? "",
  appBaseUrl: process.env.APP_BASE_URL ?? "",
  authBaseUrl: process.env.BETTER_AUTH_BASE_URL ?? "",
  authSecret: process.env.BETTER_AUTH_SECRET ?? "",
  mercadoPagoAccessToken: process.env.MERCADOPAGO_ACCESS_TOKEN ?? "",
  mercadoPagoWebhookSecret: process.env.MERCADOPAGO_WEBHOOK_SECRET ?? "",
  mercadoPagoRecurringAmount: Number(process.env.MERCADOPAGO_RECURRING_AMOUNT ?? 997),
  mercadoPagoRecurringCurrency: process.env.MERCADOPAGO_RECURRING_CURRENCY ?? "BRL",
  mercadoPagoRecurringFrequency: Number(process.env.MERCADOPAGO_RECURRING_FREQUENCY ?? 1),
  mercadoPagoRecurringFrequencyType:
    process.env.MERCADOPAGO_RECURRING_FREQUENCY_TYPE ?? "months",
  mercadoPagoPlanReason:
    process.env.MERCADOPAGO_PLAN_REASON ?? "Assinatura Maxtabil",
  uploadsDir: process.env.UPLOADS_DIR ?? "",
  smtpHost: process.env.SMTP_HOST ?? "",
  smtpPort: Number(process.env.SMTP_PORT ?? 0),
  smtpUser: process.env.SMTP_USER ?? "",
  smtpPass: process.env.SMTP_PASS ?? "",
  smtpFrom: process.env.SMTP_FROM ?? "",
  googleClientId: process.env.GOOGLE_OAUTH_CLIENT_ID ?? "",
  googleClientSecret: process.env.GOOGLE_OAUTH_CLIENT_SECRET ?? "",
  googleRedirectUri: process.env.GOOGLE_OAUTH_REDIRECT_URI ?? "",
};
